### ISSUE TITLE
Support `list` and `listitem`

### ISSUE THREAD

**Issue by Raynos** [eps1lon/dom-accessibility-api#233]
I tried to use dom testing library with `getByRole('listitem', { name: 'text' })`

I realized that querying a button by accessibility name works but the function computeAccessibleName when called on `<span role='listitem'>text</span>` returns empty string

**Comment by eps1lon** [comment]
[`listitem`](https://www.w3.org/TR/wai-aria-1.2/#listitem) only allows naming from "author". For the accessible name the contents are ignored. Only `aria-label` and `aria-labelledby` work.

I strongly advise against adding `aria-label` just to be able to query by accessible name. Test the implications with assistive technology first.

Related discussion in w3c/aria: https://github.com/w3c/aria/issues/1117

**Comment by Raynos** [comment]
I basically came here from https://stackoverflow.com/a/61669469/419970

I noticed that `getByText` does not work with a span but does work with `getByRole` so I thought `getByRole` was a good replacement for `getByText`

I guess `getByRole` is good for getting buttons that are kind of static but not for dynamic text in `<p>` or `<span>` or `<li>`

**Comment by Raynos** [comment]
I also came from https://github.com/testing-library/dom-testing-library/issues/201#issuecomment-543666815 

Where it says `getByRole` would help.

**Comment by eps1lon** [comment]
> I guess getByRole is good for getting buttons that are kind of static but not for dynamic text in <p> or <span> or <li>

ByRole is for querying elements with an accessible role with the option to filter by their name. Most elements have one but not `listitem`.

I think we can close since it is working as intended.
