### ISSUE TITLE
No matching version found for dom-accessibility-api@^0.5.0.

### ISSUE THREAD

**Issue by DenRedsky** [eps1lon/dom-accessibility-api#381]
Hello, latest version is not found in npm, It was specified as a dependency of '@testing-library/dom' so, can u publish package please)

**Comment by eps1lon** [comment]
It's listed on the npm registry: https://www.npmjs.com/package/dom-accessibility-api/v/0.5.0

What registry are you using? Could you include the exact error and steps to reproduce it?

**Comment by DenRedsky** [comment]
> What registry are you using?

Ohhh, your right, default registry was reassigned.
