### ISSUE TITLE
Value of input[type=submit] is ignored in determining accessible name

### ISSUE THREAD

**Issue by HarrisonB** [eps1lon/dom-accessibility-api#405]
It seems like even an `input[type=submit]` element has a defined `value`, one gets the localized string for "submit" despite what the spec says.

**Comment by eps1lon** [comment]
> one gets the localized string for "submit" despite what the spec says.

Could you link the section of the spec that says otherwise? And please include the markup, computed name right now, and what you expect the current name would be.

**Comment by HarrisonB** [comment]
[Relevant section of the spec](https://www.w3.org/TR/html-aam-1.0/#input-type-button-input-type-submit-and-input-type-reset-accessible-name-computation):

>  1.  If the control has an aria-label or an aria-labelledby attribute the accessible name is to be calculated using the algorithm defined in Accessible Name and Description: Computation and API Mappings 1.1.
>  1.  Otherwise use the value attribute.
>  1. For input type=submit: If steps 1 to 2 do not yield a usable text string, the accessible name is a localized string of the word "submit".
>  1. For input type=reset: If steps 1 to 2 do not yield a usable text string, the accessible name is a localized string of the word "reset".
>   1. Otherwise use title attribute.
>   1. If none of the above yield a usable text string there is no accessible name.

Right now step (2) in the algorithm is being ignored for `<input type=submit>` elements. For example, the accessible name of `<input type=submit value="Save Changes">` should be "Save Changes" but this library currently gives "Submit".

**Comment by eps1lon** [comment]
@HarrisonB Thanks for the report. Should be fixed in `0.5.2` alongside some fixes for `<input type="image" />`.
