### ISSUE TITLE
Accessible name incorrect when <slot> involved

### ISSUE THREAD

**Issue by geoffrich** [eps1lon/dom-accessibility-api#423]
I want to use this package to determine the accessible name of an element containing a slot (or when the node used to determine accessible name contains a slot, e.g. with aria-labelledby). Currently `computeAccessibleName` does not return the same accessible name the browser uses when called on an element containing a slot. I've created [a GitHub repo demonstrating the issue](https://github.com/geoffrich/accname-slot-demo).

The demo creates two custom elements, each containing a button with a slot. The second element (custom-button-with-default) sets a default value for the slot, while the first (custom-button) does not. The test code invokes `computeAccessibleName` on the `<button>` within each custom element's shadow root.

The test cases are as follows:
- When called on the button within `custom-button`, this package returns an empty string while Firefox/Chrome determines the accessible name to be "Custom name"
- When called on the button within the first `custom-button-with-default` (slot content is set), this package returns "Default name" while Firefox/Chrome determines the accessible name to be "Custom name"
- When called on the button within the second `custom-button-with-default` (slot content is not set), this package returns "Default name" while Firefox/Chrome determine the accessible name to be "Default name"

Below is an image how Firefox displays the accessibility tree. You can also clone and run my demo locally.
![Image of accessibility tree from demo page in firefox](https://user-images.githubusercontent.com/4992896/92666379-eac8f280-f2bd-11ea-8d5f-9e24d7537feb.png)

This is an interesting one, since I couldn't find a corresponding WPT and the spec doesn't cover this. I have [an issue out on the accessible name spec to clarify this](https://github.com/w3c/accname/issues/93). Either way, there does seem to be a mismatch between how this package determines the accessible name and how browsers do (at least Chrome and Firefox, I'm not able to test Safari).

The root cause of the issue seems to be related to how slots work. The "Custom name" text passed to the custom-button does not become a child node of the slot, but rather an assigned node. This package (and the spec) only consider child nodes. 

```js
const slot = document.querySelector('custom-button').shadowRoot.querySelector('slot')
console.log(slot.childNodes)        // NodeList []
console.log(slot.assignedNodes())   // Array [ #text "Custom name" ]
```

To accurately determine the accessible name with slotted content, assigned nodes should be considered as well as child nodes. We'd also need to be careful of [the case where default content is provided to the slot](https://github.com/w3c/accname/issues/93#issuecomment-689871535).

I'd be happy to take a crack at implementing this if you agree that it's an issue.

**Comment by eps1lon** [comment]
> I'd be happy to take a crack at implementing this if you agree that it's an issue.

So far I'm matching `accname` and only deviate if web-platform-tests are failing. If some part of HTML is not covered by `accname` then I'd like to prioritize actual assistive technology. Chrome and Firefox sometimes have a faulty implementation as well in their dev tools.

Ideally we'd have a codesandbox or some other testable fixture (a cloneable repro isn't very ergonomic) which we can use with NVDA or JAWS or VoiceOver. We should match their output for HTML that is not covered by `accname`.

**Comment by geoffrich** [comment]
Okay, I threw my demo into a code sandbox here: https://cwy0j.csb.app/. It renders the three test cases outlined above and shows what dom-accessibility-api returns for each one.

I tested it with both NVDA/Firefox and iOS Safari/VoiceOver. Both NVDA and VoiceOver read out the following when navigating to each button:
```
Custom name  button  
Custom name  button  
Default name  button  
```

Does that work better to demonstrate the test cases?

**Comment by eps1lon** [comment]
> Does that work better to demonstrate the test cases?

Thanks :+1: 

Would greatly appreciate a fix since I rarely have to deal with the shadow DOM.

**Comment by geoffrich** [comment]
Sounds good -- I'll have time to submit a PR within the next couple weeks.

**Comment by eps1lon** [comment]
> Sounds good -- I'll have time to submit a PR within the next couple weeks.

Great. Assigning your just so that I can easier keep track on what needs work and what doesn't.
