### ISSUE TITLE
Errors when using with rollup + svelte

### ISSUE THREAD

**Issue by blackshadev** [eps1lon/dom-accessibility-api#733]
Hi I use Rollup and svelte for my project and this liberary (as a dependancy of "@testing-library#jest-dom") causes roll-up to complain:

First a Circular dependency on module basis. It isn't circular when you look at the functions so a minor moving of the  `getLocalName` or `hasAnyConcreteRoles` would do the trick
```
(!) Circular dependency
node_modules/dom-accessibility-api/dist/util.mjs -> node_modules/dom-accessibility-api/dist/getRole.mjs -> node_modules/dom-accessibility-api/dist/util.mjs
```

Second an error about the package.json, basically you would need to add the package.json to the export class in it's own file. 
```
[rollup-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
```

I have no clue if you find this at all helpful, but if nobody provides you this feedback, you will never know that Svelte + Rollup doesn't like your package ;)

**Comment by eps1lon** [comment]
Could you provide a reproduction? I do integration testing with several build setups so by this point it might just be an issue with rollup.

**Comment by blackshadev** [comment]
I do not have a minimal reproduction, but I do have this issue in my application:
https://github.com/blackshadev/littledivelog-app-svelte

You can run `yarn --frozen-lockfile` `yarn dev` on it should raise both issues.

**Comment by eps1lon** [comment]
> I do not have a minimal reproduction, but I do have this issue in my application:
blackshadev/littledivelog-app-svelte

In order to be able to work on this issue, I need a minimal reproduction. I would  suggest stripping more and more parts of your repository until the problem no longer reproduces.

**Comment by blackshadev** [comment]
Sorry man, I don't see that going to happen, I do not use your API directly.  I use @testing-library/jest-dom which uses your API. asking me for a minimal reproduction would  still invoke `@testing-library/jest-dom`. 
Both the errors are roll-up compile erros. so a minimal repro for me is just add `import @testing-library/jest-dom;` to in `index.ts` and compile it with rollup + svelte

**Comment by eps1lon** [comment]
If you're not interested in providing code that I can debug, we can close this issue.

**Comment by CharltonC** [comment]
@eps1lon 
Thanks for developing this library. I recently run into minor issues during bundling. In my initial findings I noticed there is another circular dependency in two files perhaps you can help confirm. Thanks.

`getRole.ts` (line 3) - importing `presentationRoles` from `util.ts`
<img width="497" height="273" alt="Image" src="https://github.com/user-attachments/assets/6772b11f-fb7f-47a8-bf95-ad34cd0da300" />

`util.ts` (line 1-4) - importing from `getRole.ts` & defining `presentationRoles`
<img width="568" height="258" alt="Image" src="https://github.com/user-attachments/assets/33f902ac-5d19-4d8d-a1e0-610313bc625d" />
* the presentationRoles doesn't seem to be used in itself.
