### ISSUE TITLE
Title attribute should not supercede text contents in accessible name computation on certain elements

### ISSUE THREAD

**Issue by rpokorny** [eps1lon/dom-accessibility-api#810]
According to https://w3c.github.io/html-aam/#button-element-accessible-name-computation , the title attribute of a `<button>` element should only be considered _after_ the button element subtree.  My interpretation of this is that when a button has both text content and a `title`, the text content should be used for the accessible name, not the title.  If you look elsewhere within that spec, you'll see that the same is true for `<a>` elements.  This is consistent with the way the accessible name is reported in the devtools of both Chrome and Firefox.  If you construct such a button and inspect it in the Accessibility tab of Chrome's devtools for instance, you'll see that in the "Name" section the `title` is farther down the list than the "Contents", and that the `title` gets crossed out when Contents are present.

In terms of the other spec, https://www.w3.org/TR/accname-1.2 , my impression is that `title` is to be considered a "Tooltip attribute" as referenced in step 2I, rather than an "attribute which defines a text alternative" as referenced in step 2D.

**Comment by eps1lon** [comment]
Thanks for the detailed issue.

Could you include a concrete markup that's currently not computed correctly?

**Comment by rpokorny** [comment]
Sure.  For `<button title="foo">click me</button>` I believe the accessible name is supposed to be "click me" but this library computes it as "foo".

**Comment by eps1lon** [comment]
So the implementation currently returns the name stopping at 2D:

> Otherwise, if the current node's native markup provides an [attribute](https://www.w3.org/TR/accname-1.2/#dfn-attribute) (e.g. title)

I guess some other spec needs to define what attributes should be considered here. Or we should make an exception for `title` because otherwise we don't need 2I.
