### ISSUE TITLE
Which version of the spec is this package supporting?

### ISSUE THREAD

**Issue by jlp-craigmorten** [eps1lon/dom-accessibility-api#936]
Apologies if the repo says and have missed it, but was curious what version of spec(s) this package is aiming to support.

E.g. in the description https://w3c.github.io/accname/ is listed which links to the working draft for 1.2 of accname.

Is the aim "bleeding edge" or latest stable?

---

As a tenuously related aside, I was curious on how might feel about updating this package to consume https://github.com/A11yance/aria-query for some of mapping population, noticed there are a number of roles that are missing from this package and outsourcing might reduce maintaince overhead (notice you're active in that repo as well @eps1lon!)

For the latest list of HTML roles see https://www.w3.org/TR/html-aam-1.0/#html-element-role-mappings (or https://www.w3.org/TR/core-aam-1.2/#mapping_role_table for the full "core" list).

**Comment by eps1lon** [comment]
> Which version of the spec is this package supporting?

Editor's draft or whatever is behind https://w3c.github.io/accname/

> As a tenuously related aside, I was curious on how might feel about updating this package to consume [A11yance/aria-query](https://github.com/A11yance/aria-query) for some of mapping population

This package won't consume aria-query but rather replace it long-term since aria-query is bloated and lags too often behind.
